packages/docs/src/guide/creating-a-database.md
packages/lyra/src/lyra.ts
packages/lyra/src/types.d.ts
packages/lyra/tests/lyra.test.ts

Now the IntelliSense will suggest only key present in the schema.

Typed search properties to match schema

---

packages/lyra/tests/__snapshots__/tokenizer.test.ts.snap
packages/lyra/tests/tokenizer.test.ts

This PR improved test coverage (#16).
Had to skip a couple of stemming tests due to an error mentioned in #18, to be fixed separately.

test(lyra): improves test coverage

---

packages/lyra/src/lyra.ts
packages/lyra/src/tokenizer.ts
packages/lyra/tests/__snapshots__/lyra.test.ts.snap
packages/lyra/tests/lyra.test.ts

feat(lyra): adds possibility to disable stemming globally

---

packages/docs/src/guide/README.md

- Replaced "how it works" incorrect url with the search page
- Added examples link

Fixed guide README

---

README.md

Opened a separate PR from #65 because this one is a quicker merge (I suppose).

docs: delete method to remove method in README.md

---

packages/lyra-docs/docs/extras/contributing.md
packages/lyra-docs/docs/introduction/_category_.json
packages/lyra-docs/docs/introduction/getting-started.md
packages/lyra-docs/docs/usage/_category_.json
packages/lyra-docs/docs/usage/creating-a-new-lyra-instance.md
packages/lyra-docs/docs/usage/deletion.md
packages/lyra-docs/docs/usage/insert-data.md
packages/lyra-docs/docs/usage/search-data.md
packages/lyra-docs/docusaurus.config.js

With a "fresher" mind I did some proof reading
and spotted some mistakes, repetition and grammatical leftovers.
Also fixed the 'Edit this page' links 👍🏽

Proof reading

---

packages/examples/with-react/package.json
packages/examples/with-react/src/App.tsx
packages/examples/with-react/src/main.tsx
packages/examples/with-react/src/types/pokemon.ts

This PR fixes #71. I've added a script that builds Lyra before running Vite to fix it.
The React example was a little bit "reviewed".
This is what it looks like now.
I want to add new examples with other frameworks (or not) such as Vue, Svelte, and Vanilla JS.

Improve React Example

---

packages/docs/docs/usage/creating-a-new-lyra-instance.md

docs: add Wikipedia link

---

packages/docs/docs/introduction/getting-started.md

small update on the docs and how to import Lyra.

docs: update on how to import Lyra

---

.github/workflows/benchmark-comparisson.yml

This workflow adds the possibility to intercept potential performance
regressions in the Pull Request
Example: https://github.com/fastify/fastify/pull/3139

chore: add benchmark-comparisson workflow

---

packages/development-repl/repl.ts

I forgot to mark my previous PR #95 as draft once I realized that some types should be polished. That's the last commit I wanted to add 😅 .

refactor: improve types in repl.ts

---

src/lyra.ts
tests/lyra.test.ts

This PR adds `batchInsert`, an async method capable of inserting a large number of documents without blocking the
event loop.
Adapted from the code written by @ShogunPanda as part of the benchmark suite (all credits to him): https://github.com/LyraSearch/lyra/commit/d0f95d789ed80de2f8ebc31eedee5e72c0a27877

feat(lyra): adds batchInsert async method

---

src/errors.ts
src/lyra.ts
src/tokenizer/index.ts
tests/lyra.test.ts
tests/tokenizer.test.ts

feat(tokenizer): makes it possible to override the default tokenizer with a custom one

---

README.md

fixes typo on readme

---

src/prefix-tree/trie.ts
src/tokenizer/diacritics.ts
src/utils.ts
tests/config/c8-local.json
tests/diacritics.test.ts
tests/lyra.test.ts

fix(trie): fixes object properties access to avoid searching through inherited props

---

examples/with-vue/src/App.vue

Fixed _id is not defined error in the mounted hook

Fixed vue example

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

In this PR I would like to add support for vscode and codespaces dev containers

feat: vscode dev container support

---

src/methods/create.ts
src/methods/insert.ts
src/methods/load.ts
src/methods/remove.ts
src/methods/search.ts
src/types.ts
tap-snapshots/tests/lyra.dataset.test.ts.test.cjs

See: https://lyrasearch.slack.com/archives/C0445CLH631/p1672748793088799

fix: Fix document counts.

---

.github/workflows/ci.yml
.gitignore
package.json
playwright.config.ts
pnpm-lock.yaml
tests/ci/playwright/browsers.spec.ts
tests/ci/playwright/index.html
tests/ci/playwright/vite.config.js

fix: closes #189 using playwright

fix: closes #189

---

src/types/facets.ts
src/types/filters.ts
tests/filters.test.ts

fix(types): fixes filter types

---

src/filters.ts

fix: filteredIDs is not iterable

---

src/errors.ts
tests/lyra.test.ts

Hey,
Really naive PR, but a start for me to contribute to open source projects.

chore(msg): fix error msg

---

CONTRIBUTING.md

feat: install instructions

---

packages/plugin-astro/src/index.ts

fix: astro windows build

---

packages/orama/src/trees/avl.ts

This PR is a complete rewrite of the current AVL implementation to avoid recursive calls at all. This will allow Orama to work on larger numbers (and array of numbers) without typical problems linked to recursion.

feat: rewrites AVL tree removing recursion at all

---

packages/docs/pages/usage/search/threshold.mdx

Changed database schema field name from title to term.

Changed Wrong Field Name in threshold.mdx

---

packages/docs/next.config.js
packages/docs/next.config.mjs
packages/docs/package.json
packages/orama/package.json
packages/plugin-astro/package.json
packages/plugin-astro/test/integration.ts
packages/plugin-astro/test/sandbox/package.json
packages/plugin-docusaurus/package.json
packages/plugin-docusaurus/test/integration.ts
packages/plugin-docusaurus/test/sandbox/package.json
packages/plugin-match-highlight/package.json
packages/plugin-parsedoc/package.json
pnpm-lock.yaml
turbo.json

This fixes E2E for Astro and Docusaurus when cutting a new version. 
It also fixes a new problem in MDX.

fix: Fixed e2e tests.

---

packages/docs/pages/internals/components.mdx
packages/orama/src/components/hooks.ts
packages/orama/src/methods/create.ts
packages/orama/src/methods/search.ts
packages/orama/src/types.ts
packages/orama/tests/search.test.ts
pnpm-lock.yaml

feat: afterSearch hook

---

packages/plugin-nextra/src/index.tsx

fix: nextra plugin - router ready check

---

packages/orama/src/components/algorithms.ts
packages/orama/src/methods/search.ts
packages/orama/tests/threshold.test.ts

This PR reworks threshold handling to make sure it works as intended.
Fixes and supersedes #417.

feat: Improved threshold handling.

---

packages/docs/pages/plugins/plugin-match-highlight.mdx

docs: adds saveWithHighlights docs

---

packages/docs/pages/internals/components.mdx

Quite easy PR, but I felt a lot of pain seeing this. 😂

fix: component.mdx docs

---

packages/orama/src/components/index.ts
packages/orama/tests/remove.test.ts

fix(orama): fixes document removal with vector properties

---

packages/orama/src/errors.ts

Fix typo in error message

---

packages/plugin-match-highlight/src/index.ts
packages/plugin-nextra/src/index.tsx

fix: searchResultWithHighlight incorrectly typed

---

packages/orama/package.json
packages/orama/src/methods/search.ts
packages/orama/src/types.ts
packages/orama/tests/search.test.ts
packages/orama/tests/type/basic.test-d.ts
packages/orama/tests/type/search.test-d.ts
pnpm-lock.yaml

Add test to types for simple cases
Add test to properties prop in SearchParams.

Add test to types

---

packages/orama/src/types.ts
packages/orama/tests/type/search.test-d.ts

Add strong type to `boost` parameter

Strong 'boost' parameter

---

packages/stopwords/scripts/build.js

Fix type definition for stopwords

---

biome.json
packages/plugin-data-persistence/src/index.ts
packages/plugin-data-persistence/test/ci/non-node-ci-runner.js
packages/plugin-data-persistence/test/index.test.ts
packages/plugin-docusaurus-v3/src/client/theme/SearchBar/index.tsx
packages/plugin-docusaurus-v3/src/client/theme/SearchBarFooter/index.tsx
packages/plugin-docusaurus-v3/src/client/theme/SearchResult/index.tsx
packages/plugin-docusaurus-v3/src/server/index.ts
packages/plugin-docusaurus-v3/src/server/translationMessages.ts
packages/plugin-docusaurus-v3/test/integration.ts
packages/plugin-parsedoc/src/index.ts
packages/plugin-parsedoc/test/index.test.ts
packages/plugin-telemetry/src/collector.ts
packages/plugin-telemetry/src/index.ts
packages/plugin-telemetry/src/polyfills.ts
packages/plugin-telemetry/src/tests/collector.test.ts
packages/plugin-telemetry/src/tests/polyfills.test.ts

Getting there! Now this PR formats:
- `plugin-parsedoc`
- `plugin-telemetry`
- `plugin-data-persistenc`
I also formatted `biome.json` file.
The CI should pass, to make sure everything is fine.

chore: format more plugins

---

.devcontainer/devcontainer.json

Devcontainer performance enhancement adopting [target named volumes](https://code.visualstudio.com/remote/advancedcontainers/improve-performance#_use-a-targeted-named-volume).
Furthermore, this enhancement avoids this [problem](https://github.com/pnpm/pnpm/issues/7024).

chore: adds volumes configuration to devcontainer

---

packages/docs/open-source/usage/search/introduction.md

ref: https://github.com/orgs/oramasearch/discussions/584

note does not support case-sensitivity

---

packages/docs/open-source/internals/components.md
packages/docs/open-source/plugins/plugin-parsedoc.md
packages/docs/open-source/plugins/writing-your-own-plugins.md
packages/docs/open-source/usage/insert.md
packages/docs/open-source/usage/search/facets.md
packages/docs/open-source/usage/search/fields-boosting.md
packages/docs/open-source/usage/search/filters.md
packages/docs/open-source/usage/search/introduction.md

While I was giving the documentation a first read, I took the opportunity to fix some errors in there 😁

Chore: fix docs

---

packages/docs/open-source/plugins/plugin-vitepress.md

Fixed the package name in import path.

Fix npm package typo in plugin-vitepress.md

---

packages/plugin-astro/src/index.ts

fix: Astro crash when using an image service #617

---

packages/docs/open-source/usage/search/hybrid-search.md
packages/orama/src/methods/search-hybrid.ts
packages/orama/src/types.ts
packages/orama/tests/search.hybrid.test.ts

Add custom weights to hybrid search

---

packages/orama/src/components/sorter.ts
packages/orama/src/components/tokenizer/languages.ts
packages/orama/tests/sort.test.ts

fix #627 string sorting crash

---

packages/plugin-astro/src/index.ts

fix: placed search index in `dist/client` not `dist` 

---

packages/orama/tests/filters.test.ts

Add test for checking what happen if I filter with empty array on string property

---

packages/plugin-docusaurus/src/client/theme/SearchBar/index.tsx
packages/plugin-docusaurus/src/server/index.ts
packages/plugin-docusaurus/src/server/types.ts

replicate the fix previously done on plugin-docusaurus-v3

fix plugin working only with default content docs id

---

packages/plugin-docusaurus-v3/README.md
packages/plugin-docusaurus-v3/package.json
packages/plugin-docusaurus-v3/src/index.ts
packages/plugin-docusaurus-v3/src/theme/SearchBar/index.css
packages/plugin-docusaurus-v3/src/theme/SearchBar/index.tsx
packages/plugin-docusaurus-v3/src/utils.ts
pnpm-lock.yaml

- Updates README (plugin-docusaurus-v3)
- Updates searchbox version (plugin-docusaurus-v3)
- Fixes version not being selected on client side (plugin-docusaurus-v3)
- Fixes CSS issues

various fixes, update searchbox, update readme

---

packages/plugin-docusaurus-v3/src/index.ts

- Fix: doing post-build op when cloud config is used

fix: check postbuild only if not cloud config

---

packages/orama/src/components/facets.ts
packages/orama/src/methods/search-hybrid.ts

With this PR I would like to improve the speed of the code related to facets retrieval and hybrid search.

perf(orama): facets and hybrid search

---

packages/plugin-docusaurus-v3/src/theme/SearchBar/index.tsx

The scope of this PR is to fix an issue related to the search box not working properly when `npm run serve` is launched.
- Add optional chaining to check if `searchData` is `undefined`

fix: searchdata not loading properly on serve

---

packages/plugin-nextra/package.json
pnpm-lock.yaml

NPM did not like the workspace, so I updated it with the latest version, also removed postbuild as the types are made automtically

Fixes for published version

---

packages/plugin-docusaurus-v3/src/index.ts

Taking over this PR - https://github.com/askorama/orama/pull/726

break when value is undefined for page type

---

packages/plugin-docusaurus-v3/src/index.ts

This address an issue reported in #728.

fix: Correctly detect development mode.

---

packages/docs/astro.config.mjs
packages/docs/package.json

- adds cookie consent banner
- updates tracking script

feat: adds cookie consent banner

---

packages/docs/src/content/docs/open-source/usage/search/filters.mdx

Fixes #767 adding documentation for filters behavior on array properties

docs: add documentation for filters behavior on array properties

---

packages/docs/config/head.ts
packages/docs/src/components/Head.astro
packages/docs/src/components/Header.astro
packages/docs/src/components/Search.tsx
packages/docs/src/content/docs/index.mdx
packages/docs/src/styles/custom.css

- fix styling for Search component (Searchbox default background)
- fix styling for mobile search experience
- other minor fixes

docs: minor fixes

---

packages/plugin-embeddings/LICENSE.md
packages/plugin-embeddings/README.md
packages/plugin-embeddings/package.json
packages/plugin-embeddings/src/index.ts
packages/plugin-embeddings/tsconfig.json
packages/plugin-embeddings/tsup.lib.js
pnpm-lock.yaml
scripts/release.mjs
turbo.json

To get started with **Orama Plugin Embeddings**, just install it with npm:
```sh
npm i @orama/plugin-embeddings
```
**Important note**: to use this plugin, you'll also need to install one of the following TensorflowJS backend:
- `@tensorflow/tfjs`
- `@tensorflow/tfjs-node`
- `@tensorflow/tfjs-backend-webgl`
- `@tensorflow/tfjs-backend-cpu`
- `@tensorflow/tfjs-backend-wasm`
For example, if you're running Orama on the browser, we highly recommend using `@tensorflow/tfjs-backend-webgl`:
```sh
npm i @tensorflow/tfjs-backend-webgl
```
If you're using Orama in Node.js, we recommend using `@tensorflow/tfjs-node`:
```sh
npm i @tensorflow/tfjs-node
```
```js
import { create } from '@orama/orama'
import { pluginEmbeddings } from '@orama/plugin-embeddings'
import '@tensorflow/tfjs-node' // Or any …
```

Feat: adds plugin for local embeddings generation at runtime

---

packages/plugin-docusaurus-v3/package.json
packages/plugin-docusaurus-v3/src/theme/SearchBar/index.tsx
packages/plugin-docusaurus-v3/src/theme/SearchBar/useOrama.ts
packages/plugin-docusaurus/package.json
packages/plugin-docusaurus/src/theme/SearchBar/index.tsx
packages/plugin-docusaurus/src/theme/SearchBar/useOrama.ts
pnpm-lock.yaml

- Moved search box and search button configurations after props to allow override.
- `facetProperty` is now overridable.
- Added search button text customization

feat: add improvements on Docusaurus Searchbox customization

---

packages/plugin-docusaurus-v3/src/index.ts
packages/plugin-docusaurus/src/index.ts

fix: docusaurus build not working if pages or blogs plugins are missing

---

packages/docs/src/content/docs/cloud/performing-search/full-text-search.mdx
packages/docs/src/content/docs/open-source/usage/search/filters.mdx
packages/orama/src/trees/flat.ts
packages/orama/src/types.ts
packages/orama/tests/enum.test.ts

https://github.com/oramasearch/orama/issues/877

Add containsAny filter operator for enum[]

---

packages/docs/src/content/docs/cloud/ui-components/search-button.mdx

- Fixes documentation for the search button component

fix: orama-search-button doc

---

packages/docs/src/content/docs/cloud/data-sources/native-integrations/docusaurus.mdx
packages/docs/src/content/docs/open-source/plugins/plugin-docusaurus.mdx
packages/plugin-docusaurus-v3/package.json
packages/plugin-docusaurus-v3/src/constants.ts
packages/plugin-docusaurus-v3/src/docusaurus.d.ts
packages/plugin-docusaurus-v3/src/index.ts
packages/plugin-docusaurus-v3/src/orama.d.ts
packages/plugin-docusaurus-v3/src/theme/SearchBar/index.tsx
packages/plugin-docusaurus-v3/src/theme/SearchBar/useOrama.ts
packages/plugin-docusaurus-v3/src/types.ts
packages/plugin-docusaurus-v3/src/utils.ts
packages/plugin-docusaurus-v3/tsconfig.json
pnpm-lock.yaml

- OSS: disable chat
- Refactored configuration variable names
- `cloud.oramaCloudAPIKey` -> `cloud.apiKey`
- `analytics` -> now under new Object `plugins` ex. `plugins.analytics` `plugins.secureProxy` etc..
- Code cleanup

Refactor: Docusaurus plugin v3 + Update documentation

---

packages/orama/tests/dataset.test.ts
packages/orama/tests/insert.test.ts
scripts/version.mjs

feat: removes JSON imports in favor of fs.readFile

---

packages/orama/src/components/tokenizer/languages.ts

Adding regex for Czech language tokenizer.

add czech language support

---

packages/orama/src/package.json
packages/orama/src/types.ts

fix: expose 'tolerance' in hybrid search

---

packages/docs/src/content/docs/open-source/plugins/plugin-secure-proxy.mdx

It seems it's either a typo or an outdated code block?

doc: update plugin-secure-proxy.mdx

---

packages/plugin-docusaurus-v3/src/theme/SearchBar/index.tsx
packages/plugin-docusaurus-v3/src/theme/SearchBar/utils.ts

Fix: preferredVersion undefined on Docusaurus start
