- packages/lyra/src/lyra.ts
closes: #6
The intended change is to be 100% backward compatible, moving the default argument into the `search` function of the index Class.
It copies the pattern used in the insert statement - and should give a more logical default behavior to searching with non-English default languages.
Thanks :pray:
> bug: default search will perform with default language - language can be specified allowing multi-lingual search

- packages/lyra/src/lyra.ts
- packages/lyra/src/prefix-tree/trie.ts
- packages/lyra/tests/lyra.test.ts
- packages/lyra/tests/trie.test.ts
This PR implements the #1 using a parameter that determinates if the search actions requires an exact match or not.
The `find` method of Trie nodes now accept an object as a single parameter. The type has been added: `FindParams`.
The solution found is to insert a check in the recursive function `findAllWords`, if the search actions requires an **exact** match and the _word_ given by the last node doesn't match with the _prefix_, returns the initial output.
I wrote the tests for this, I'm considering add more tests if necessary.
> Exact match

- packages/docs/src/guide/search.md
This PR would add the (missing) documentation for **Exact Match**, inside the _Search_ section.
The `elapsed` time was computed using the following machine:
- OS: macOS Monterey
- Vendor: Mac
- Chip: Apple M1
- Memory: 16GB
> Docs: Exact Match

- packages/lyra/tests/utils.test.ts
This PR includes the tests for **Utils** module.
The tested methods are:
- formatBytes
- formatNanoseconds
The current coverage for the utils is:
| File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s |
| --------- | ------- | -------- | ------- | ------- | ----------------- |
| All files | 82.57   | 61.53    | 86.84   | 82.67   |                   |
| utils.ts  | 52.63   | 33.33    | 66.66   | 52.63   | 4-11,22,30        |
After the tests:
| File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s |
| --------- | ------- | -------- | ------- | ------- | ----------------- |
| All files | 85.49   | 63.51    | 89.47   | 85.71   |                   |
| utils.ts  | 94.73   | 83.33    | 100     | 94.73   | 30                |
> Utils test

- packages/lyra/src/lyra.ts
- packages/lyra/tests/lyra.test.ts
This is the PR for the issue #14 
Coverage pre PR:
File             | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                 
-----------------|---------|----------|---------|---------|-----------------------------------
All files        |   86.44 |    68.13 |      90 |   87.14 |                                   
src             |   82.43 |    58.18 |   84.61 |   82.38 |                                   
errors.ts      |    82.6 |      100 |      50 |      75 | 8,20,23,26                        
levenshtein.ts |   91.66 |       60 |     100 |     100 | 2-3                               
lyra.ts        |   89.71 |    65.62 |     100 |   89.71 | 76-81,113,150-153,168,179,238,270 
stemmer.ts     |   30.76 |    18.18 |     100 |   30.76 | 22-23,28-49,56 …
> Support for nested schema

- package.json
- packages/benchmarks/engines/prefix-search-movies.js
- packages/benchmarks/index.js
With this PR I would like to improve the benchmark package, that currently isn't working.
Even after this, the `title.csv` required by `prefix-search-movies` is still missing.
> fix(benchmark start command): bennchmark start command and files import

- packages/lyra/src/lyra.ts
- packages/lyra/src/types.d.ts
- packages/lyra/tests/lyra.test.ts
As per https://github.com/nearform/lyra/issues/14#issuecomment-1186160234 this PR aims to  type the insert method so the developer will know at compile time if the document inserted does not match the schema.
Code coverage:
File             | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s   
-----------------|---------|----------|---------|---------|---------------------
All files        |   87.95 |    72.82 |      90 |   89.04 |                     
src             |   84.68 |    66.07 |   84.61 |    85.2 |                     
errors.ts      |    82.6 |      100 |      50 |      75 | 8,20,23,26          
levenshtein.ts |   91.66 |       60 |     100 |     100 | 2-3                 
lyra.ts        |   93.69 |    78.78 |     100 |   94.54 | 118,155-158,173,184 
stemmer.ts …
> Typed Lyra.insert method according to the schema used

- packages/lyra/src/lyra.ts
This PR fixes #29.
The solution is to add, before the return statement, a filter by `Boolean`, so undefined elements are filtered.
After doing several benchmarks between `filter` method, `dynamic array`, and the current solution, the result makes the filter method more performant.
Let me show you some data.
> Inserting **100K** elements, search something, and limit by _1_.
**Current fixed allocation array**
```js
{ elapsed: '80μs', hits: [ undefined ], count: 0 } { timeSpent: '1072ms' }
```
**Dynamic allocation array**
```js
{ elapsed: '82μs', hits: [], count: 0 } { timeSpent: '1117ms' }
```
**Filtering results**
```js
{ elapsed: '75μs', hits: [], count: 0 } { timeSpent: '1080ms' }
```
> Inserting **1M** elements, search something, and limit by _10_.
```js
{
elapsed: '79μs',
hits: [ …
```
> Prevent undefined elements

- packages/lyra/src/prefix-tree/trie.ts
- packages/lyra/tests/lyra.test.ts
This PR fixes #39 and #40.
I've implemented a new param in the `removeDocByWord` method used in `remove` method to prevent removing words that not exactly matches the document's word.
I also added 2 cases to the tests.
> Add exact param in remove doc by word method

- packages/lyra/src/prefix-tree/trie.ts
- packages/lyra/tests/lyra.test.ts
This PR would fix #40.
Thanks a lot to @lucaong for supporting me in this bug.
The `removeByWord` now considers if the **docID** exists in _docIDs_ Set, then set the `node.end` as `false`. 
The `exact` param will stay in the function for future implementations.
> Remove by word should consider other doc ids

- packages/lyra/src/prefix-tree/trie.ts
This should prevent unnecessary linear time computations 
(the potential perf improvement is proportional to the docIDs size)
> perf: prevent potential overhead on falsy value

- packages/benchmarks/benchmark-table/index.mjs
fixing the *.mjs file which is responsible of a typo into the packages/benchmark/README.md 
(referring #50 )
> fix: A typo into the generating of README.md file

- packages/docs/src/components/LyraDemo/index.tsx
- packages/docs/src/components/LyraDemo/style.module.css
This PR would improve the current design of `Live Demo` page.
This is how looks:
It's really simple and clean. I'm considering creating a more dynamic page adding the DB structure and searching by schema properties with a different design. 
**Mobile**
> Style live demo page

- packages/lyra/src/lyra.ts
I have added docs only for the four major functions. Once the writing style gets a green flag I would be happy to document all the other stuff.
> docs: add inline documentation

- packages/development-repl/repl.ts
- packages/lyra/tests/lyra.dataset.test.ts
**EDIT:** Now I'm not so sure if it's a good idea to propose these changes, as `repl.ts` seems to be kinda "out of reach" for the type checker, and I might be introducing some difficult-to-detect problems until that is solved in the first place.
The changes of this PR are merely cosmetic, but I find it a good thing to have a smaller amount of warnings when we run the linter :) .
> refactor: fix some minor linter warnings

- src/utils.ts
> fix: check for hrtime func availability

- src/lyra.ts
Currently, the `batchInsert` function uses `setImmediate` to schedule the recursive `insert` calls to avoid blocking the event loop.
However, this causes the API to break in the browsers where `setImmediate` is not defined as it's a Node API.
This PR fixes that issue by using `setTimeout` with a delay of `0`.
cc// @micheleriva
> fix: replace setImmediate with setTimeout

- src/insertion-checker.ts
Fixes a crash when running on React-Native which does have `process` but not `process.emitWarning`.
> fix(insertion-checker): fix crash when warning on react-native

- package.json
part of #117 that removes broken npm run scripts that appear to have been left over from when this was a monorepo
> chore(package): remove broken npm run scripts

- package.json
As noted in the [npm docs](https://docs.npmjs.com/cli/v8/using-npm/scripts#life-cycle-scripts), if a package has a `prepare` script, it will be executed before packaging when installing directly from git or github.
**This allows `npm install LyraSearch/lyra` directly as a GitHub URL in consuming packages.** It also allows `npm install git+https://github.com/LyraSearch/lyra.git`. Without this change, the `dist` folder will not be installed when installing from git or github.
**This allows consuming packages to install the latest from main, during development instead of waiting for a release**  🎉 
**Note:** This begs the question if the `build` script should be using `pnpm`. I think a follow-up PR is merited to use `npm` directly for `build` and `prepare` scripts, making the package as …
> build(package): builds the package on prepare, allowing for git dependencies

- package.json
If installing via git or github (not the published package on npm), it doesn't make sense to require pnpm. For better or worse, npm is the standard.
> build(package): use npm for build to allow for vanilla install from git and github

- .github/workflows/release.yml
- .github/workflows/tests.yml
Adds https://github.com/nearform/optic-release-automation-action and takes the chance to refactor the existing CI script, which was unnecessarily complex.
> chore: release automation

- src/levenshtein.ts
- src/prefix-tree/trie.ts
- tests/levenshtein.test.ts
As discussed privately, I have noticed that the `levenshtein` distance is currently only used as a comparison metric to check whether two strings have edit distance less than a given `tolerance` threshold.
Computing the `levenshtein` metric in the general case takes time `O(max(m, n))` and space `O(max(m, n))`, where `m` and `n` is the length of the two input strings. When we're only interested in retrieving the exact edit distance when it's below or equal to a given `tolerance` threshold, more time-efficient methods exist.
Given
```ts
let term: string;
let word: string;
let tolerance: number; // small, non-negative integer
```
this PR turns the comparison
```ts
if (levenshtein(term, word) <= tolerance) {
// ...
}
```
into the following:
```ts
if (boundedLevenshtein(term, word, …
```
> feat(lyra): compute levenshtein metric within a given tolerance

- README.md
* Attempted to make the various builds a bit more clear.
* Added the interesting browser import method (thanks to @mateonunez in #136 )
> docs(readme): document the different builds

- src/lyra.ts
- tests/lyra.test.ts
This PR closes #154.
The `recursiveTrieInsertion` method invokes a `return` statement immediately after the call of the self-recursion method.
This impacts not only the objects, but also all the properties that you want to insert after the first object is inserted.
By removing the `return', the procedure will consider the other properties following the right insertion strategy.
> perf(lyra): support multiple nested props

- package.json
- pnpm-lock.yaml
I've noticed the `typescript` dependency hadn't been updated in a while.
Updating to `typescript@4.9.3` didn't require any code change in this repository.
I'd expect compilation times to be slightly faster with this new version.
> chore: updated to typescript@4.9.3

- src/errors.ts
- src/methods/create.ts
- src/methods/insert.ts
- src/methods/remove.ts
- src/methods/search.ts
- tap-snapshots/tests/insert.test.ts.test.cjs
- tests/insert.test.ts
- tests/lyra.edge.test.ts
Highly requested feature, will solve both #220 and #112.
By default, Lyra will check if a field `id` exists in the document we're trying to insert:
```js
insert(db, {
id: 'foo-0123', // Will use this ID
user: 'mitch'
})
```
if the `id` field does not exist, it will generate a random one.
We can also override the default `id` field by passing a function to the `insert` configuration:
```js
insert(db, {
id: 'foo-0123',
user: 'mitch'
}, {
id: (doc /* the entire document */) => `${doc.user}.01`
})
```
in that case, the `id` will be `mitch.01`. The `id` configuration function can be either sync or async.
> feat(insert): adds custom ID capabilities

- src/radix-tree/radix.ts
- src/utils.ts
- tests/utils.test.ts
This PR would replace the `Object.hasOwn` method by using a simple polyfill. This implementation makes Lyra compatible with **Node v14**.
It would be great for Lyra to be used in as many runtimes as possible.
If this PR would be merged it would be useful to add the tests on specific Node versions such as v14, v16, and v18.
The tests were updated by adding the Unit Test to the `getOwnProperty` util method.
> perf(utils): prevent Object.hasOwn from not being defined

- package.json
- src/methods/common.ts
- src/radix-tree/node.ts
- tsconfig.json
This PR fixes types when using TypeScript via CommonJS modules. It introduces a breaking change in TypeScript, as follows:
```diff
- import { create, insert, search } from '@lyrasearch/lyra';
- import { stemmer } from '@lyrasearch/lyra/stemmer/it';
- import { requireLyraInternals } from '@lyrasearch/lyra/internals';
+ import { create, insert, search } from '@lyrasearch/lyra/cjs';
+ import { stemmer } from '@lyrasearch/lyra/cjs/stemmer/it';
+ import { requireLyraInternals } from '@lyrasearch/lyra/cjs/internals';
``` 
We basically have to manually tell TypeScript to get types and functions from CommonJS files.
Fixes #243
> fix(types): fixes cjs types

- src/algorithms.ts
- src/errors.ts
- src/methods/create.ts
- src/methods/search.ts
- src/types.ts
- tests/boosting.test.ts
This PR introduces a field-boosting API, which allows you to boost research when a given search term string appears in one of the desired fields. Example:
```js
import { create, insert, search } from "@lyrasearch/lyra";
schema: {
author: "string",
quote: "string",
meta: {
tags: "string",
}
}
})
// insert stuff...
await insert(...)
await insert(...)
await insert(...)
await search({
term: "John Doe",
boost: {
author: 1.5,
"meta.tags": 1.1
}
})
```
The configuration above will boost `author` and `meta.tags` respectively by `1.5` and `1.1`.
Still a work in progress, will switch to percentage-based boosting before merging.
> feat(search): adds fields boosting interface

- src/facets.ts
- src/methods/create.ts
- src/methods/search.ts
- src/types.ts
- src/utils.ts
- tests/facets.test.ts
This PR aims to add support for facets while searching with Lyra.
The API is pretty straightforward and will likely close https://github.com/LyraSearch/lyra/issues/206, and pave the ground for https://github.com/LyraSearch/lyra/issues/212.
Given the following database, we'll now need to select which fields will be available while performing a facet query:
```js
schema: {
id: "string",
brand: "string",
model: "string",
year: "number",
price: "number",
used: "boolean",
available: "boolean",
}
});
```
Now let's insert some data. I'm experimenting with a format similar to the following one:
```jsonl
{"id":"3e4e0dc3-7cb9-4a03-9a36-2c66f51e08c9","brand":"Acura","year":2000,"model":"TL","available":true,"used":false,"price":36899}, …
```
> Feat: adds facets to search

- src/tokenizer/index.ts
- tests/lyra.dataset.test.ts
- tests/lyra.test.ts
- tests/snapshots/events.json
It should resolve this issue:
[Issue](https://github.com/LyraSearch/lyra/issues/230)
I changed only the languages that used the same pattern (du-en-it). I added three unit tests and it seems correct for me, but I wait for your considerations. Thanks
> feat: update regex tokenizer (en-du-it)

- src/filters.ts
- src/methods/create.ts
- src/methods/insert.ts
- src/methods/remove.ts
- src/types/filters.ts
- src/types/index.ts
- tests/filters.test.ts
This PR adds boolean indexing and filters to Lyra search:
```js
import { create, insert, search } from '@lyrasearch/lyra'
schema: {
name: 'string',
favorite: 'boolean'
}
})
await insert(db, { ... });
await insert(db, { ... });
await insert(db, { ... });
await search({
term: 'the prestige',
where: {
favorite: true
}
})
```
> feat(filters): adds boolean filters

- examples/with-vue/package.json
Relatives paths in Vue example seemed to be wrong. I changed them and now 
**npm run dev** on vue-example folder is ok.
> fix: Vue example with wrong build script

- README.md
- packages/docs/pages/usage/search/introduction.mdx
- packages/orama/README.md
- packages/orama/src/components/defaults.ts
- packages/orama/src/methods/search.ts
- packages/orama/src/types.ts
- packages/orama/tests/elapsed.test.ts
- packages/orama/tests/main.test.ts
This PR introduces a small change in the returning value of the `search` function.
`search` used to return the following object:
```js
{
elapsed: bigint,
hits: [...],
counts: number,
...
}
```
but the bigint type is not serializable in JSON and causes a lot of trouble.
This PR changes the `search` function behavior by returning an object for the `elapsed` property, with the following shape:
```js
{
elapsed: {
raw: 181208,            // type: number
formatted: `181μs` // type: string
}
}
```
> feat(elapsed): refactors elapsed time to return an object

- packages/plugin-astro/package.json
Fixes the npm package link to the github repo.
> fix: Astro plugin repository link typo

- packages/orama/src/trees/radix.ts
I think `currentCharacter in root.children` is the same as checking if `const rootChildCurrentChar = root.children[currentCharacter]` is truthy
> fix: repeated operation radix.ts

- packages/docs/pages/plugins/index.md
There was a wrong link on the plugins page, this PR fixes it. For issue https://github.com/oramasearch/orama/issues/370.
> docs: fix link on plugins page

- packages/plugin-astro/src/index.ts
- packages/plugin-astro/test/integration.ts
- packages/plugin-astro/test/sandbox/astro.config.mjs
- packages/plugin-astro/test/sandbox/src/content/posts/article.md
- packages/plugin-astro/test/sandbox/src/content/posts/foobar.md
- packages/plugin-astro/test/sandbox/src/content/posts/foobar2.md
- packages/plugin-astro/test/sandbox/src/pages/[...blog]/[...inner]/index.astro
This PR fixes #366 
After all the investigation reported in the issue, I noticed that static pages are working fine but dynamic routes are not provided by Astro after the build.
With this PR I grab the path of the dist folder by taking the first route, then I compose the path of all other pages from that.
To validate if it works I added three dynamic pages and a new database with a pattern matcher in the sandbox project. Only the page matching the pattern is indexed, as expected. I also expanded the integration tests and they're still passing.
If this makes some kind of sense I'm happy to discuss it here or on Slack!
I'll be really happy to be able to use Orama on my Astro blog with dynamic pages :D
> feat:add support for dynamic pages to plugin-astro

- packages/docs/pages/plugins/plugin-astro.mdx
As mentioned [on slack](https://orama-community.slack.com/archives/C0445CLH631/p1683237965615909), I added a few words about the `astro dev` limitations and `astro build` + `astro preview` solution.
> docs: add local development instructions in plugin-astro

- packages/plugin-astro/src/index.ts
- packages/plugin-astro/test/integration.ts
- packages/plugin-astro/test/sandbox/astro.config.mjs
- packages/plugin-astro/test/sandbox/src/pages/404.astro
- packages/plugin-astro/test/sandbox/src/pages/nested/page.astro
It's me again! :)
After installing the plugin on my blog I noticed in some cases astro does not generate pages as `dist/path/to/404/index.html` but directly `dist/404.html` which wasn't covered in #375.
I noticed this happened with `404.astro` as it becomes `404.html` while `a404.astro `becomes `a404/index.html`
---
I improved the path handling in the script to detect these cases and properly handle them
As usual, I added a test, this time with a permissive matcher to make sure 404 is handled and no errors are thrown.
> fix: handle pages that are not generated inside a folder

- packages/docs/pages/usage/remove.mdx
- packages/orama/src/methods/insert.ts
- packages/orama/src/methods/remove.ts
- packages/orama/src/methods/update.ts
- packages/orama/tests/remove.test.ts
- packages/orama/tests/update.test.ts
This PR introduces those changes:
- `remove` method returns false if the document is not found
- `removeAll` returns the number of the removed documents
- `updateMany` doesn't remove the documents if some of them are invalid
> Rework *Multiple methods

- packages/orama/src/trees/avl.ts
The current implementation is different than the [old implementation that was recursive](https://github.com/oramasearch/orama/commit/f5e8254ed8203176a17e6d095d91a207060c2c3d#diff-08a9a2514d28f29e668d1ec4cf824b22c5bead9ac9abfb5ed7c6a250f854f8d1L147-L154), actually, the old implementation was faster than the current implementation!
But, I refactored this current implementation to match the old one without the recursion.
```
isBalancedOriginal x 6,168,383 ops/sec ±1.53% (87 runs sampled)
isBalancedOptimizedV4 x 13,253,321 ops/sec ±1.14% (90 runs sampled)
```
<details>
<summary>benchmark.ts</summary>
```ts
import benchmark from 'benchmark';
import { create, insert, Node } from './src/trees/avl.js';
const tree = create(1, { foo: 'bar' })
insert(tree, 2, { foo: 'qux' })
insert(tree, 3, { foo: …
```
> perf: faster isBalanced AVL Tree method

- packages/orama/src/trees/avl.ts
Since `getBalanceFactor` is used in one place, don't have the necessity of having a function with switch statement, just get the diff of the height and then compare directly.
I also removed the unused StackNode type.
> perf: skip get balance factor

- packages/orama/src/trees/radix.ts
- packages/orama/src/utils.ts
- packages/orama/tests/snapshots/events.json
There is currently no reason for `radix` to have an `id` or `parent` property, so can we remove it?
This breaks a test in `dataset.test.ts`, but breaks the order of the `snapshot`, from what I can see the documents are just being returned in a different order than expected.
> perf: remove unused properties from radix

- README.md
- packages/docs/pages/_meta.json
- packages/docs/pages/index.mdx
- packages/docs/pages/usage/create.mdx
- packages/docs/pages/usage/search/_meta.json
- packages/docs/pages/usage/search/vector-search.mdx
- packages/orama/README.md
- packages/orama/src/cjs/index.cts
- packages/orama/src/components/cosine-similarity.ts
- packages/orama/src/components/defaults.ts
- packages/orama/src/components/index.ts
- packages/orama/src/components/sorter.ts
- packages/orama/src/errors.ts
- packages/orama/src/index.ts
- packages/orama/src/methods/insert.ts
- packages/orama/src/methods/search-vector.ts
- packages/orama/src/methods/search.ts
- packages/orama/src/types.ts
- packages/orama/tests/cosine-similarity.test.ts
- packages/orama/tests/create.test.ts
- packages/orama/tests/search-vector.test.ts
- packages/orama/tests/sort.test.ts
- packages/plugin-data-persistence/src/server.ts
- packages/plugin-data-persistence/test/index.test.ts
- scripts/release.mjs
This PR introduces vector search capabilities in Orama. This will be part of Orama `v1.2.0`, the next major release.
Orama adds support for Vector search by adding a new datatype: `vector[<size>]`:
```js
import { create } from '@orama/orama'
schema: {
text: 'string',
embedding: 'vector[1536]' // <--- vector size is mandatory here. OpenAI embeddings, for instance, have 1536 dimensions. 
}
})
```
After you create your Orama instance, you can insert and search for vectors using the new `searchVector` function:
```js
import { create, insert, searchVector } from '@orama/orama'
schema: {
text: 'string',
myVector: 'vector[5]'
}
})
await insert(db, { text: 'foo', myVector: [1, 0, 0, 0, 0] })
await insert(db, { text: 'bar', myVector: [0, 0, 0, 0, …
```
> Adds vector search capabilities to Orama

- packages/orama/src/methods/serialization.ts
Hi @micheleriva, this is a simple proposal that fixes https://github.com/oramasearch/orama/issues/467.
Not sure if you wanted to persist more of the tokenizer config.
> set tokenizer language during load

- packages/plugin-match-highlight/src/commonjs.cts
- packages/plugin-match-highlight/src/index.ts
- packages/plugin-match-highlight/test/index.test.ts
See here for context: https://github.com/oramasearch/orama/issues/446#issuecomment-1693672265
New to the project so apologies if this isn't the right approach. It's extending the native `save()` and `load()` since `"positions"` is not present and included in either. It does the raise question of how this would work if you had multiple plugins that needed to extend the base `Orama` object?
Another approach could be by passing an array of the attributes you wanted the base `save()` and `load()` to include.
Fixes #446
> Add `saveWithHighlight` and `loadWithHighlight`

- packages/orama/src/components/index.ts
We discovered a bug while using search.where with multi token criterias. With the previous logic, only the first token was used for search.
My following pull request includes a test that was failing without this fix.
ex: defining these 4 documents:
```js
const id1 = await insert(db, {
name: 'super coffee maker',
rating: 5,
price: 900,
meta: {
sales: 100,
finish: 'black matte',
},
})
const id2 = await insert(db, {
name: 'washing machine',
rating: 5,
price: 900,
meta: {
sales: 100,
finish: 'gloss black',
},
})
const id3 = await insert(db, {
name: 'coffee maker',
rating: 3,
price: 30,
meta: {
sales: 25,
finish: 'gloss blue',
},
})
const id4 = await insert(db, {
name: 'coffee maker deluxe',
rating: 5,
price: 45,
meta: {
sales: 25,
finish: 'blue matte',
},
})
```
And doing this search:
```js …
```
> search on all token during where searches

- packages/orama/src/components/index.ts
- packages/orama/src/components/tokenizer/index.ts
- packages/orama/src/types.ts
- packages/orama/tests/tokenizeSkipProperties.test.ts
I want to used facet search but many of the values we have are multi-word-token (ie. "black matte") that needs to be searched without tokenization, not only stemming but no split at all.
I added a new optionnal parameter that replicate the stemmingSkipProperties that was already in place.
If a property is matched, then no splitting occurs on the matching prop.
> Tokenize skip properties

- packages/orama/src/components/groups.ts
- packages/orama/src/components/index.ts
- packages/orama/src/methods/search.ts
- packages/orama/src/trees/avl.ts
- packages/orama/src/utils.ts
Closes #301 
I just have a simple issue with the `.push`.
I added a function instead of just the if statement because probably `orama` can have other parts with the same issue.
PS: To be able to test/run the script on #301 without taking several minutes/hours, merge this branch with #434.
> fix: issue with max call stack when search

- packages/docs/pages/index.mdx
- packages/docs/pages/usage/create.mdx
- packages/docs/pages/usage/insert.mdx
- packages/docs/pages/usage/search/filters.mdx
- packages/docs/pages/usage/search/introduction.mdx
- packages/orama/src/components/defaults.ts
- packages/orama/src/components/index.ts
- packages/orama/src/components/sorter.ts
- packages/orama/src/errors.ts
- packages/orama/src/methods/insert.ts
- packages/orama/src/trees/flat.ts
- packages/orama/src/types.ts
- packages/orama/tests/enum.test.ts
- packages/orama/tests/serialization.test.ts
- packages/plugin-data-persistence/test/index.test.ts
We collect some issues for our performance during the insertion. In particular, the number type has some problems if the number of documents is high. But also string can be slow too. 
The issue related to the insertion time is because of the cost of keeping the order for the number. Trees allow us to keep order with the cost of O(log(N)) for insertion time. But what happens if we choose to lose the order to have a faster insertion time?
Depending on what you need, values can have a lot of meanings:
- strings you want to search for
- numbers you want to compare with operators (`>`, `<`, `>=`, `<=`, `=`, `!=`)
- enum you want to compare with operators (`=`, `in`)
This PR introduces the `enum` type to allow:
- fast insertion
- fast search
- `=` and `in` operator (others??)
- reduce the dump …
> Implement enum type

- packages/plugin-nextra/src/index.tsx
As the title says, I noticed that the `cmd+k` shortcut is missing.
> fix(plugin-nextra): add missing cmd+k keybinding to focus the input search

- packages/docs/pages/usage/create.mdx
- packages/docs/pages/usage/search/facets.mdx
- packages/docs/pages/usage/search/filters.mdx
- packages/orama/src/components/defaults.ts
- packages/orama/src/components/facets.ts
- packages/orama/src/components/index.ts
- packages/orama/src/components/sorter.ts
- packages/orama/src/errors.ts
- packages/orama/src/methods/insert.ts
- packages/orama/src/trees/flat.ts
- packages/orama/src/types.ts
- packages/orama/tests/enum.test.ts
- packages/orama/tests/facets.test.ts
- packages/plugin-data-persistence/test/index.test.ts
With this PR, I want to introduce the `enum[]` as the follower of #458
So,
```javascript
schema: {
colors: 'enum[]',
},
})
await insertMultiple(db, [
{colors: ['green', 'red'] },
{colors: ['green'] },
{colors: ['blue', 'white'] },
])
const resultContains = await search(db, {
term: '',
where: {
colors: { contains: 'green' },
}
}) // Expected 2 results: 1° and 2°
const resultIntersects = await search(db, {
term: '',
where: {
colors: { intersects: ['red', 'blue'] },
}
}) // Expected 2 results: 1° and 3°
```
This PR introduces `contains`, and `intersects` operators because they are more appropriate for arrays.
> Implements enum[]

- packages/plugin-match-highlight/src/index.ts
- packages/plugin-match-highlight/test/index.test.ts
Fixes #464.
In order to make using the `boundedLevenshtein` function easier, I refactored the `searchWithHighlight` function to take a more imperative/callback-less approach.
> fix(plugin-match-highlight): support tolerance parameter in searchWithHighlight

- packages/plugin-docusaurus/src/server/index.ts
Exporting these two functions because they could be helpful for other packages based on Orama.
> add export to transformFn and defaultToSectionSchema

- packages/orama/src/methods/create.ts
- packages/orama/src/trees/radix.ts
- packages/orama/tests/search.test.ts
/claim #480
Added a testcase for the (issue #480). 
Confirmed bug by testcase fail.
Added Levenshtein distance calculation on radix tree.
distance on tree is only calculated if exact option is not used and tolerance>0. (existing logic is used if tolerance is 0 or exact is true)
Confirmed all testcases(including added testcase of #480) passed.
> Fix string tolerance option (#480)

- packages/plugin-match-highlight/src/index.ts
The current way the `SearchResultWithHighlight` type is constructed ends up losing type info if you use an array method to iterate over `hits`. I made a [TypeScript playground demo](https://www.typescriptlang.org/play?#code/FAehAIBcE8AcFMDO4BmAnA9gW3AIgAIZoCGWxIRpxuwMC4ASkgK4A2kAPACIYDGzWeADtIAPnABecAG9g4eeACWAEwBc4RJDSKhAcwDcchYl5F46oQIBG8NIYXhlfAcMjqe-QSMMBfQ3XhGFnZEbmcvMUkZI3lTZhELa1t7BQALRUhEdSZENk4PFxFRAG0AXRT5MHB4VmJYRHg1cABRWvrGgBVFQQrwKpRiXnhMgH51ADFB4Zy88AAfcHjleBQdRt6q3UxmerHwAHFt2Bn2MM9XcQWllbXlX0NQCADkdGw8QhIyEFhWZl0dAC0ZEgvFSAPSulSrEUkMgNB0kFsAyG4AAChhEBlFBghNEHJpiGg3OBLFgbHYYuBWMJdJBUokyclgD5gI9wABhZhoNCuKBwcxsgLgADK8EJoJOkAA6hlUgAJGFQxWcSUFCLiKSS0Kq8IXcAAMmiVQc6Uy6gAFJKODrzkUDUaIA4HLAMVicVkgqY0MoOJptHoADSeog+v06XRB9GYyDYoRlUSiQzGhQ+ACUZSTED8rKqqMwLoayg0GF+MZxqlo-KCuXYMrpUbdQ …
> fix(plugin-match-highlight): `SearchResultWithHighlight` type improvement

- packages/orama/src/methods/create.ts
- packages/orama/tests/search.test.ts
Fixes #492.
Correctly create the tokenizer using the custom one passed via parameters.
Speaking about the linked issue, the provided example seems to be wrong:
```ts
const orama = await create({
schema: {
foo: "string",
},
components: {
tokenizer: {
normalizationCache: new Map([["english:foo:Bar", "bar"]]),
stemming: true,
},
},
});
```
According to the documentation, a custom tokenizer is made up of at least `language`, `normalizationCache`, and the `tokenize` function (see [Tokenizer](https://github.com/oramasearch/orama/blob/main/packages/orama/src/types.ts#L730) interface). For the time being, passing a custom `normalizationCache` is only possible if a custom tokenizer is used.
Passing a custom normalisation cache with default values without using a custom `tokenize` function could be …
> fix: create custom tokenizer

- packages/docs/pages/open-source/text-analysis/stemming.mdx
- packages/orama/tests/tokenizer.test.ts
- packages/stemmers/README.md
- packages/stemmers/scripts/build.js
> feat: export language with each stemmer

- packages/orama/src/trees/radix.ts
To improve performance, I fixed some for-loops where the length was recalculated at each iteration, instead of calculating it just once before the loop itself.
Reviewer: @micheleriva
> chore: avoid recalculating lengths in some for-loops

- biome.json
- package.json
- packages/plugin-vitepress/src/index.ts
- pnpm-lock.yaml
Hi peeps, how are you? 👋 
I am proposing an alternative to Prettier, Biome. https://biomejs.dev/formatter/
My idea is to slowly adopt the tool, and slowly adopt also linter (alongside eslint for the time being) and import sorting.
The PR only applies changes to `plugin-vitepress` as a starting point. I am happy to guide the migration to the rest of the code base.
While I was replacing it, I realized that prettier isn't used in the code base, so I changed the biome options to meet `ts-standard` - the library that Michele uses. However, there are still some differences due to some inconsistencies in the code.
Let me know what you guys think. If the change is welcomed, we could use this PR to decide the formatting style of the code base.
Thank you :)
> chore: use biome to format code

- packages/orama/src/components/index.ts
- packages/orama/tests/search.test.ts
Fixes #601 
I also conducted some speed tests for the search function after this implementation, and the speed results were the same. I made sure that it had no effect on search speed.
I am not entirely sure that this PR won't create some inconsistencies in the codebase. Therefore, a check from the development team would be highly appreciated.
Also, closed #602 due to committing on wrong branch.
> Fix #601 - Skipping of keys in Object.prototype in search function

- packages/docs/open-source/usage/search/hybrid-search.md
Currently refers to undefined `searchVector` function
> Fix typo in hybrid-search doc

- packages/orama/src/methods/search-fulltext.ts
- packages/orama/src/methods/search-hybrid.ts
This PR fixes issue #641 where relevancy params where in wrong order in `Object.assign`
> Fix wrong order of params

- packages/orama/src/components/algorithms.ts
This PR is a suggestion to fix #642. Instead of two sets, one for token counts and one for scores we combine them into a single set. Now when sorting the list it guarantees that they're in right order. Read further information and try the test case of a bug on Replit, mentioned in the issue #642
> Fix to get threshold 0 working as documented

- packages/docs/open-source/internals/components.md
Fixed a typo in the example snippet for the `validateSchema` component
> docs: fix typo in components doc

- packages/plugin-docusaurus-v3/src/index.ts
- packages/plugin-docusaurus-v3/src/theme/SearchBar/index.tsx
Fixing an issue, @SaraVieira pointed out while working on Deno.
Adding the support to multiple instances of Plugin content docs (Ref. https://docusaurus.io/docs/docs-multi-instance)
> fix plugin working only with default content docs id

- packages/plugin-vitepress/src/index.ts
This pull request adds the missing base property in the vitepress plugin. If there is no base, it defaults to an empty string. Additionally, I removed the trailing slash to avoid any potential path issues (I had the issue in my own vitepress).
It should fixes #604
> fix(plugin-vitepress): add missing userConfig.base in the page path

- packages/orama/src/utils.ts
In the browser there's no "process", and this throws an error in strict mode.
> Fix getNanosecondsTime when process is not defined

- packages/docs/cloud/data-sources/custom-integrations/introduction.md
In the Orama Cloud docs Custom Integrations Webhook doc is marked as WIP https://docs.askorama.ai/cloud/data-sources/custom-integrations/introduction.html but in reality REST API are WIP, while Webhook section seems to be ready.
P.S.: there's nothing in contribution guidelines about directly editing page from GH, so no template for this PR :D
> docs: updated docs to correctly show what section in wip

- packages/orama/src/trees/avl.ts
As suggested by title, I've converted lessThan and greaterThan (avl tree) using stack instead of recursion.
Couldn't find a way to achieve the same thing with rangeSearch without altering the order of the result
> remove recursion in avl trees

- packages/orama/src/components/index.ts
- packages/orama/src/methods/search-fulltext.ts
- packages/plugin-docusaurus-v3/src/index.ts
- packages/plugin-vitepress/src/index.ts
As a perf improvement, use `flatMap` instead of `.map(...).flat`
> perf(orama): prefer flatMap

- packages/plugin-vitepress/src/index.ts
Prevents plugin from breaking when a page doesn't have an h1
closes https://github.com/askorama/orama/issues/701
> [Plugin Vitepress] fix case when item has no h1

- packages/plugin-data-persistence/src/server.ts
This is how I fixed issue #649 earlier. This should ignore the Deno https import when Next.js project is bundled with Webpack. 
@algora-pbc /claim #649
> Ignore deno import with webpack

- packages/plugin-docusaurus-v3/package.json
- packages/plugin-docusaurus-v3/src/index.ts
- pnpm-lock.yaml
Implements #751.
Adds fragments to links generated from doc sections.
Supports autogenerated and explict header ids in markdown files.
> Add header fragment support for plugin-docusaurus-v3

- packages/docs/src/content/docs/open-source/plugins/plugin-docusaurus.mdx
The deploy configuration in the initial example of the documentation is true. will cause the user to copy directly and cause the compilation to fail. Adding a configuration type enumeration and a link to the relevant type will help users use the deploy type more quickly.
The recommended initial configuration can be changed to default
> docs(plugin-docusaurus-v3):  detail for deploy type

- packages/docs/package.json
- packages/docs/src/components/Search.jsx
- pnpm-lock.yaml
Adds the new searchbox.
It has some issues, but next release should fix most of them.
> chore: use new searchbox

- packages/plugin-docusaurus-v3/src/index.ts
- packages/plugin-docusaurus-v3/src/theme/SearchBar/useOrama.ts
Fixes #728. 
Now on a fresh docusaurus install running `npm run build` then `npm run start` or `npm run serve` should display results correctly.
> Fix issues with `plugin-docusaurus-v3` detecting local mode.

- packages/plugin-secure-proxy/README.md
- packages/plugin-secure-proxy/src/index.ts
With this PR, Orama OSS will be able to generate embeddings at insert-time via the Secure Proxy plugin.
```js
import { create, insert } from '@orama/orama'
import { pluginSecureProxy } from '@orama/plugin-secure-proxy'
const secureProxy = pluginSecureProxy({
apiKey: 'xyz',
embeddings: {
defaultProperty: 'embeddings',
model: 'orama/gte-small',
onInsert: {
generate: true, // Generate the embeddings at insert-time
properties: ['name', 'data.age'],
verbose: true
},
},
chat: {
model: 'openai/gpt-4o'
}
})
schema: {
name: 'string',
data: {
age: 'number'
},
embeddings: 'vector[384]'
},
plugins: [secureProxy]
})
await insert(db, { name: 'Michele', age: 29 })
// since "verbose" is set to `true`, it will log:
// Generating embeddings for properties name, data.age : …
```
> feat: generate embeddings on insert via Secure Proxy plugin

- packages/switch/LICENSE.md
- packages/switch/README.md
- packages/switch/package.json
- packages/switch/src/index.ts
- packages/switch/tsconfig.json
- packages/switch/tsup.config.ts
- pnpm-lock.yaml
With Orama Switch, you can use the same APIs to access either Orama Cloud or Orama OSS.
For instance, this is how you would interact with Orama Cloud:
```js
import { Switch } from '@orama/switch'
import { OramaClient } from '@oramacloud/client'
const client = new OramaClient({
endpoint: '<Your Orama Cloud Endpoint>',
api_key: '<Your Orama Cloud API Key>',
})
const orama = new Switch(client)
const results = await orama.search({
term: 'noise cancelling headphones',
where: {
price: {
lte: 99.99
}
}
})
```
And this is Orama OSS:
```js
import { Switch } from '@orama/switch'
import { create } from '@orama/orama'
schema: {
productName: 'string',
price: 'number'
}
})
const orama = new Switch(client)
const results = await orama.search({
term: 'noise cancelling …
```
> feat: adds new package (Orama Switch)

- packages/orama/src/components/index.ts
- packages/orama/tests/remove.test.ts
@AdventureBeard I'm making a release today so I'm opening a PR to speed this up!
> fix: fixes zero division when computing scores after removing all documents from an index

- packages/docs/src/content/docs/cloud/orama-ai/orama-secure-proxy.mdx
- packages/docs/src/content/docs/open-source/plugins/plugin-secure-proxy.mdx
- packages/docs/src/content/docs/open-source/supported-languages/index.mdx
- packages/docs/src/content/docs/open-source/usage/search/hybrid-search.mdx
- packages/docs/src/content/docs/open-source/usage/search/vector-search.mdx
fix: remove `.html` from links
> docs: fix broken links

- packages/docs/src/content/docs/cloud/performing-search/index.mdx
Fix typo: Add missing "of" in SDK usage description
Changed "using one our Official SDKs" to "using one of our Official SDKs" to improve grammar and clarity.
> docs: fixes typos

- packages/plugin-docusaurus/src/theme/SearchBar/useOrama.ts
- Disable chat on OSS, due to secure proxy feature missing (will be added later)
> fix: disabled chat on local due secure proxy feat missing

- .github/workflows/turbo.yml
> fix: usage of `a deprecated Node.js version` in CI

- packages/switch/package.json
- packages/switch/src/index.ts
- pnpm-lock.yaml
A simple PR to:
- Update the `@oramacloud/client` version inside the `switch` package
- Fix the condition to check if an instance of OramaClient is passed due to an `instanceof` not being correct if the instance is created outside the project where the switch is imported.
> Fix: Switch OramaClient condition + update dependency version

- packages/plugin-astro/src/index.ts
Astro v5.0 updates the shape of `IntegrationRouteData.distURL` to be undefined or an array of URLs.
Fixes #862
> fix: Astro 5 Compatibility

- packages/docs/src/content/docs/cloud/integrating-orama-cloud/official-sdk.mdx
Fix wrong URL for JavaScript SDK
> Fix wrong URL to JS SDK

- packages/orama/src/components/index.ts
- packages/orama/src/methods/search-fulltext.ts
- packages/orama/src/types.ts
- packages/orama/tests/threshold.test.ts
> Fix: #850 add threshold logic back

- packages/tokenizers/package.json
This pull request includes a small change to the `packages/tokenizers/package.json` file. The change updates the `files` field to include the `dist` directory instead of the `build` directory.
> fix: fixes tokenizers directory

- packages/docs/src/content/docs/open-source/usage/search/filters.mdx
- packages/orama/src/components/index.ts
- packages/orama/src/internals.ts
- packages/orama/src/types.ts
- packages/orama/src/utils.ts
- packages/orama/tests/filters.test.ts
With Orama you can combine multiple filters using logical operators like `and`, `or`, and `not`.
- `and`: this operator accepts an array of filters. All conditions must be true.
- `or`: this operator accepts an array of filters. At least one condition must be true.
- `not`: this operator accepts a single filter. The condition must be false.
All operators can be nested.
This filter will return all documents that have the category `"electronics"`:
```javascript copy
const results = search(db, {
term: "phone",
where: {
category: "electronics"
}
})
```
This filter will return all documents that have the category `"electronics"` and the price less than `100`:
```javascript copy
const results = search(db, {
term: "phone",
where: {
category: "electronics",
price: { lt: 100 }
}
})
```
With the …
> feat: adds explicit AND, OR, NOT filters

- packages/stopwords/README.md
The current one is https://docs.orama.com/docs/orama-js/text-analysis/stop-words
> Update stopwords docs URL
